name: Build
run-name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: |
          ./copy-sqlite3-src.sh
      - run: |
          cmake . && make
          